#!/usr/bin/env bash
# =============================================================================
# auto-handoff.sh — Session Export Automation for AI Agents
# =============================================================================
#
# Usage:
#   ./export-sessions-ghosty/auto-handoff.sh           # interactive (asks for notes)
#   ./export-sessions-ghosty/auto-handoff.sh "notes"    # with inline notes
#   ./export-sessions-ghosty/auto-handoff.sh "notes" --no-pdf  # skip PDF generation
#
# Convention:
#   export-DD-MM-YYYY-HH-MM-appname.{md,pdf}
#
# This script:
#   1. Reads project context (git log, status, diff)
#   2. Generates a timestamped markdown handoff
#   3. Optionally converts to PDF via pandoc + xelatex
#   4. Prints the output path so AI agents can ingest it
#
# Token Exhaustion Protocol:
#   When an AI agent has ~5% remaining tokens, it should call this script,
#   present the result to the user, and suggest a fresh session.
#
# Installation (one-time):
#   Place this script in the project's export-sessions-<app>/ directory.
#   Make it executable: chmod +x auto-handoff.sh
#
# For editors/agents without /handoff command support, add this to your
# .opencode/skills/ or .claude/skills/ directory as a slash command.
# =============================================================================

set -euo pipefail

# --- Config ---
APP_NAME="ghosty"
PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
EXPORT_DIR="${PROJECT_ROOT}/export-sessions-${APP_NAME}"
TIMESTAMP=$(date "+%d-%m-%Y-%H-%M")
OUTPUT_BASE="${EXPORT_DIR}/export-${TIMESTAMP}-${APP_NAME}"
OUTPUT_MD="${OUTPUT_BASE}.md"
OUTPUT_PDF="${OUTPUT_BASE}.pdf"

USER_NOTES="${1:-}"
SKIP_PDF=false
for arg in "$@"; do
  [ "$arg" == "--no-pdf" ] && SKIP_PDF=true
done

mkdir -p "${EXPORT_DIR}"

# --- Gather context ---
echo "[handoff] Gathering project state..."

# Git history
GIT_LOG=$(cd "${PROJECT_ROOT}" && git log --oneline -20 2>/dev/null || echo "(no git history)")
GIT_STATUS=$(cd "${PROJECT_ROOT}" && git status --short 2>/dev/null || echo "(no git status)")
GIT_DIFF=$(cd "${PROJECT_ROOT}" && git diff --stat 2>/dev/null || echo "(no diff)")
GIT_BRANCH=$(cd "${PROJECT_ROOT}" && git branch --show-current 2>/dev/null || echo "unknown")
GIT_REMOTE=$(cd "${PROJECT_ROOT}" && git remote get-url origin 2>/dev/null || echo "unknown")

# Python env
PYTHON_VERSION=$(python3 --version 2>/dev/null || echo "unknown")
UV_VERSION=$(uv --version 2>/dev/null || echo "uninstalled")
PIP_LIST=$(cd "${PROJECT_ROOT}" && uv pip list 2>/dev/null || pip list 2>/dev/null || echo "(no pip)")

# Project version
PROJECT_VERSION=$(cd "${PROJECT_ROOT}" && python3 -c "
try:
    from pathlib import Path
    import tomllib
    data = tomllib.loads(Path('pyproject.toml').read_text())
    print(data.get('project', {}).get('version', 'unknown'))
except:
    print('unknown')
" 2>/dev/null || echo "unknown")

# --- Build the handoff ---
cat > "${OUTPUT_MD}" << HANDOFF_EOF
# Handoff — ${APP_NAME}
**Generated**: $(date "+%d-%m-%Y %H:%M")  
**Project**: ${APP_NAME} v${PROJECT_VERSION}  
**Branch**: ${GIT_BRANCH}  
**Remote**: ${GIT_REMOTE}  
**Python**: ${PYTHON_VERSION}  
**uv**: ${UV_VERSION}

---

## Recent Commits (last 20)
\`\`\`
${GIT_LOG}
\`\`\`

## Working Tree Status
\`\`\`
${GIT_STATUS}
\`\`\`

## Uncommitted Changes (summary)
\`\`\`
${GIT_DIFF}
\`\`\`

## Session Summary
HANDOFF_EOF

if [ -n "${USER_NOTES}" ]; then
  echo "" >> "${OUTPUT_MD}"
  echo "${USER_NOTES}" >> "${OUTPUT_MD}"
else
  echo "" >> "${OUTPUT_MD}"
  echo "*[No notes provided — run with a summary argument to populate]*" >> "${OUTPUT_MD}"
fi

cat >> "${OUTPUT_MD}" << 'HANDOFF_EOF'

## Dependency Snapshot
```
HANDOFF_EOF
echo "${PIP_LIST}" >> "${OUTPUT_MD}"
echo '```' >> "${OUTPUT_MD}"

cat >> "${OUTPUT_MD}" << 'HANDOFF_EOF'

## Key Decisions Made This Session
*(Fill this in when continuing or from the previous handoff)*

## Pending / Next Steps
*(Fill this in when continuing or from the previous handoff)*

## Checksums
HANDOFF_EOF
MD5SUM=$(md5 -q "${OUTPUT_MD}" 2>/dev/null || md5sum "${OUTPUT_MD}" 2>/dev/null || echo "n/a")
echo "MD5: ${MD5SUM}" >> "${OUTPUT_MD}"

echo "" >> "${OUTPUT_MD}"
echo "---" >> "${OUTPUT_MD}"
echo "_Auto-generated by auto-handoff.sh at $(date '+%Y-%m-%d %H:%M:%S')_" >> "${OUTPUT_MD}"

echo "[handoff] ✓ Markdown saved: ${OUTPUT_MD}"

# --- Generate PDF ---
if [ "${SKIP_PDF}" = false ] && command -v pandoc &>/dev/null && command -v xelatex &>/dev/null; then
  echo "[handoff] Generating PDF via pandoc + xelatex..."
  TEMPLATE_DIR="${EXPORT_DIR}/.pandoc-templates"
  mkdir -p "${TEMPLATE_DIR}"

  pandoc "${OUTPUT_MD}" \
    --pdf-engine=xelatex \
    --from markdown+yaml_metadata_block \
    -o "${OUTPUT_PDF}" \
    --metadata title="Ghosty Handoff — ${TIMESTAMP}" \
    --metadata author="auto-handoff.sh" \
    --metadata date="$(date '+%d-%m-%Y %H:%M')" \
    -V colorlinks=true \
    -V linkcolor=purple \
    -V geometry:margin=1in \
    2>/dev/null && echo "[handoff] ✓ PDF saved: ${OUTPUT_PDF}" || echo "[handoff] ⚠ PDF generation failed (pandoc error — md saved anyway)"
elif [ "${SKIP_PDF}" = true ]; then
  echo "[handoff] ⚠ PDF skipped (--no-pdf flag)"
else
  echo "[handoff] ⚠ PDF skipped (pandoc or xelatex not found)"
  echo "          Install: brew install pandoc && brew install --cask mactex-no-gui"
fi

echo ""
echo "============================================================================="
echo " HANDOFF COMPLETE"
echo "============================================================================="
echo " Markdown: ${OUTPUT_MD}"
[ -f "${OUTPUT_PDF}" ] && echo " PDF:      ${OUTPUT_PDF}"
echo ""
echo " To resume in a new session, provide this path to the AI agent:"
echo "   ${OUTPUT_MD}"
echo "============================================================================="
